version: '3.8'

services:
  robo:
    build: .
    container_name: robo_tareffa
    restart: unless-stopped
    environment:
      # Preencha suas credenciais do Tareffa diretamente no painel do Coolify 
      # na aba Environment Variables (estas aqui são apenas de exemplo)
      - TAREFFA_USER=miguel@scalcomt.com.br
      - TAREFFA_PASS=Scalco123
      - TZ=America/Cuiaba
    volumes:
      - volume_pastamonitorada_v4:/sv-scalco/Sistemas/GED/PastaMonitorada
      - volume_protocolo_v4:/sv-scalco/Protocolo
      - volume_cnpj_v4:/sv-scalco/Trabalho/Contabilidade/Miguel/Miguel_Certificados/1/CNPJ

volumes:
  volume_pastamonitorada_v4:
    driver_opts:
      type: cifs
      o: "username=micro11,password=micro14,vers=2.0,dir_mode=0777,file_mode=0777,uid=0,gid=0,noperm"
      device: "//192.168.1.195/Sistemas/GED/PastaMonitorada"

  volume_protocolo_v4:
    driver_opts:
      type: cifs
      o: "username=micro11,password=micro14,vers=2.0,dir_mode=0777,file_mode=0777,uid=0,gid=0,noperm"
      device: "//192.168.1.195/Trabalho/Contabilidade/P r o t o c o l o"

  volume_cnpj_v4:
    driver_opts:
      type: cifs
      o: "username=micro11,password=micro14,vers=2.0,dir_mode=0777,file_mode=0777,uid=0,gid=0,noperm"
      device: "//192.168.1.195/Trabalho/Contabilidade/Miguel/Miguel_Certificados/1/CNPJ"
